# Generated by Django 4.2.3 on 2024-05-11 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderrecieved',
            name='item_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
